name: Medialmark
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd9d4'
    - '#aaa19c'
    - '#8e8580'
    - '#504b51'
    - '#2d292b'
  brandStrength: 0.1895707086659968
  lightness: 0.8228573175147176
  saturation: 0.955768586602062
  rhythmicContrast: 0.6651775056961924
purpose: []
